@baseurl = https://api.cognitive.microsofttranslator.com
@api-key = 16ba8168c878454bb39e88a45375846d
@region = eastus


### Translate Text
POST {{baseurl}}/translate?api-version=3.0&to=zh-Hans&to=es&to=ja
Ocp-Apim-Subscription-Key: {{api-key}}
Ocp-Apim-Subscription-Region: {{region}}
Content-Type: application/json

[
  {
    "Text": "Hello, what is your name?"
  }
]

### Translite Text
POST {{baseurl}}/transliterate?api-version=3.0&language=ja&fromScript=Jpan&toScript=Latn
Ocp-Apim-Subscription-Key: {{api-key}}
Ocp-Apim-Subscription-Region: {{region}}
Content-Type: application/json

[
  {
    "Text": "こんにちは"
  }
]
